#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Endpoints.Routes.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MotoApp_v1")]
	public partial class RoutesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRoute(Route instance);
    partial void UpdateRoute(Route instance);
    partial void DeleteRoute(Route instance);
    partial void InsertPopularRoute(PopularRoute instance);
    partial void UpdatePopularRoute(PopularRoute instance);
    partial void DeletePopularRoute(PopularRoute instance);
    #endregion
		
		public RoutesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MotoApp_v1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RoutesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoutesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoutesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoutesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NewRoute> NewRoutes
		{
			get
			{
				return this.GetTable<NewRoute>();
			}
		}
		
		public System.Data.Linq.Table<Coordinates> Coordinates
		{
			get
			{
				return this.GetTable<Coordinates>();
			}
		}
		
		public System.Data.Linq.Table<Route> Routes
		{
			get
			{
				return this.GetTable<Route>();
			}
		}
		
		public System.Data.Linq.Table<newSharedRoute> newSharedRoutes
		{
			get
			{
				return this.GetTable<newSharedRoute>();
			}
		}
		
		public System.Data.Linq.Table<PopularRoute> PopularRoutes
		{
			get
			{
				return this.GetTable<PopularRoute>();
			}
		}
		
		public System.Data.Linq.Table<RoutePhoto> RoutePhotos
		{
			get
			{
				return this.GetTable<RoutePhoto>();
			}
		}
		
		public System.Data.Linq.Table<SocialRoute> SocialRoutes
		{
			get
			{
				return this.GetTable<SocialRoute>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_MOT_Ruta")]
	public partial class NewRoute
	{
		
		private System.DateTime _start;
		
		private System.DateTime _end;
		
		private System.Nullable<int> _duration;
		
		private System.Nullable<decimal> _distance;
		
		private System.Nullable<decimal> _speed;
		
		private System.Nullable<decimal> _calories;
		
		private System.Nullable<decimal> _lat;
		
		private System.Nullable<decimal> _lng;
		
		private System.Nullable<decimal> _altitude;
		
		private string _image;
		
		private List<Coordinates> _coordinates;
		
		private int _pauses;
		
		public NewRoute()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Inicio", Storage="_start", DbType="DateTime NOT NULL")]
		public System.DateTime start
		{
			get
			{
				return this._start;
			}
			set
			{
				if ((this._start != value))
				{
					this._start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Fin", Storage="_end", DbType="DateTime NOT NULL")]
		public System.DateTime end
		{
			get
			{
				return this._end;
			}
			set
			{
				if ((this._end != value))
				{
					this._end = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Duracion", Storage="_duration", DbType="Int NOT NULL")]
		public System.Nullable<int> duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this._duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Distancia", Storage="_distance", DbType="Decimal(18,5) NOT NULL")]
		public System.Nullable<decimal> distance
		{
			get
			{
				return this._distance;
			}
			set
			{
				if ((this._distance != value))
				{
					this._distance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Velocidad", Storage="_speed", DbType="Decimal(18,5) NOT NULL")]
		public System.Nullable<decimal> speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this._speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Calorias", Storage="_calories", DbType="Decimal(18,5) NOT NULL")]
		public System.Nullable<decimal> calories
		{
			get
			{
				return this._calories;
			}
			set
			{
				if ((this._calories != value))
				{
					this._calories = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Latitud", Storage="_lat", DbType="Decimal(18,9) NOT NULL")]
		public System.Nullable<decimal> lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this._lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Longitud", Storage="_lng", DbType="Decimal(18,9) NOT NULL")]
		public System.Nullable<decimal> lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				if ((this._lng != value))
				{
					this._lng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Altitud", Storage="_altitude", DbType="Decimal(18,5) NOT NULL")]
		public System.Nullable<decimal> altitude
		{
			get
			{
				return this._altitude;
			}
			set
			{
				if ((this._altitude != value))
				{
					this._altitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Imagen", Storage="_image", DbType="VarChar(2048) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this._image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coordinates", CanBeNull=false)]
		public List<Coordinates> coordinates
		{
			get
			{
				return this._coordinates;
			}
			set
			{
				if ((this._coordinates != value))
				{
					this._coordinates = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Pausas", Storage="_pauses")]
		public int pauses
		{
			get
			{
				return this._pauses;
			}
			set
			{
				if ((this._pauses != value))
				{
					this._pauses = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_MOT_Coordenada")]
	public partial class Coordinates
	{
		
		private decimal _lat;
		
		private decimal _lng;
		
		private decimal _altitude;
		
		private decimal _speed;
		
		private decimal _distance;
		
		private decimal _duration;
		
		private System.DateTime _createdAt;
		
		public Coordinates()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COOR_Latitud", Storage="_lat", DbType="Decimal(18,9) NOT NULL")]
		public decimal lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this._lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COOR_Longitud", Storage="_lng", DbType="Decimal(18,9) NOT NULL")]
		public decimal lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				if ((this._lng != value))
				{
					this._lng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COOR_Altitud", Storage="_altitude", DbType="Decimal(18,5) NOT NULL")]
		public decimal altitude
		{
			get
			{
				return this._altitude;
			}
			set
			{
				if ((this._altitude != value))
				{
					this._altitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COOR_Velocidad", Storage="_speed", DbType="Decimal(18,5) NOT NULL")]
		public decimal speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this._speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COOR_Distancia", Storage="_distance", DbType="Decimal(18,5) NOT NULL")]
		public decimal distance
		{
			get
			{
				return this._distance;
			}
			set
			{
				if ((this._distance != value))
				{
					this._distance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COOR_Duracion", Storage="_duration", DbType="Decimal(18,5) NOT NULL")]
		public decimal duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this._duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COOR_Fecha", Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this._createdAt = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VT_MOT_Rutas")]
	public partial class Route : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _token;
		
		private System.DateTime _start;
		
		private System.DateTime _end;
		
		private decimal _altitude;
		
		private decimal _lat;
		
		private decimal _lng;
		
		private decimal _calories;
		
		private decimal _distance;
		
		private int _duration;
		
		private int _pauses;
		
		private string _image;
		
		private decimal _speed;
		
		private int _isShared;
		
		private string _shared_name;
		
		private System.Nullable<int> _shared_likes;
		
		private string _shared_observations;
		
		private System.Nullable<System.DateTime> _shared_createdAt;
		
		private string _sensation_name;
		
		private System.Guid _sensation_token;
		
		private string _sensation_identifier;
		
		private System.DateTime _createdAt;
		
		private System.Guid _creator_token;
		
		private string _creator_identifier;
		
		private string _creator_photo;
		
		private string _fullname;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntokenChanging(System.Guid value);
    partial void OntokenChanged();
    partial void OnstartChanging(System.DateTime value);
    partial void OnstartChanged();
    partial void OnendChanging(System.DateTime value);
    partial void OnendChanged();
    partial void OnaltitudeChanging(decimal value);
    partial void OnaltitudeChanged();
    partial void OnlatChanging(decimal value);
    partial void OnlatChanged();
    partial void OnlngChanging(decimal value);
    partial void OnlngChanged();
    partial void OncaloriesChanging(decimal value);
    partial void OncaloriesChanged();
    partial void OndistanceChanging(decimal value);
    partial void OndistanceChanged();
    partial void OndurationChanging(int value);
    partial void OndurationChanged();
    partial void OnpausesChanging(int value);
    partial void OnpausesChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnspeedChanging(decimal value);
    partial void OnspeedChanged();
    partial void OnisSharedChanging(int value);
    partial void OnisSharedChanged();
    partial void Onshared_nameChanging(string value);
    partial void Onshared_nameChanged();
    partial void Onshared_likesChanging(System.Nullable<int> value);
    partial void Onshared_likesChanged();
    partial void Onshared_observationsChanging(string value);
    partial void Onshared_observationsChanged();
    partial void Onshared_createdAtChanging(System.Nullable<System.DateTime> value);
    partial void Onshared_createdAtChanged();
    partial void Onsensation_nameChanging(string value);
    partial void Onsensation_nameChanged();
    partial void Onsensation_tokenChanging(System.Guid value);
    partial void Onsensation_tokenChanged();
    partial void Onsensation_identifierChanging(string value);
    partial void Onsensation_identifierChanged();
    partial void OncreatedAtChanging(System.DateTime value);
    partial void OncreatedAtChanged();
    partial void Oncreator_tokenChanging(System.Guid value);
    partial void Oncreator_tokenChanged();
    partial void Oncreator_identifierChanging(string value);
    partial void Oncreator_identifierChanged();
    partial void Oncreator_photoChanging(string value);
    partial void Oncreator_photoChanged();
    partial void Oncreator_fullnameChanging(string value);
    partial void Oncreator_fullnameChanged();
    #endregion
		
		public Route()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Token", Storage="_token", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Inicio", Storage="_start", DbType="DateTime NOT NULL")]
		public System.DateTime start
		{
			get
			{
				return this._start;
			}
			set
			{
				if ((this._start != value))
				{
					this.OnstartChanging(value);
					this.SendPropertyChanging();
					this._start = value;
					this.SendPropertyChanged("start");
					this.OnstartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Fin", Storage="_end", DbType="DateTime NOT NULL")]
		public System.DateTime end
		{
			get
			{
				return this._end;
			}
			set
			{
				if ((this._end != value))
				{
					this.OnendChanging(value);
					this.SendPropertyChanging();
					this._end = value;
					this.SendPropertyChanged("end");
					this.OnendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Altitud", Storage="_altitude", DbType="Decimal(18,5) NOT NULL")]
		public decimal altitude
		{
			get
			{
				return this._altitude;
			}
			set
			{
				if ((this._altitude != value))
				{
					this.OnaltitudeChanging(value);
					this.SendPropertyChanging();
					this._altitude = value;
					this.SendPropertyChanged("altitude");
					this.OnaltitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Latitud", Storage="_lat", DbType="Decimal(18,9) NOT NULL")]
		public decimal lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Longitud", Storage="_lng", DbType="Decimal(18,9) NOT NULL")]
		public decimal lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				if ((this._lng != value))
				{
					this.OnlngChanging(value);
					this.SendPropertyChanging();
					this._lng = value;
					this.SendPropertyChanged("lng");
					this.OnlngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Calorias", Storage="_calories", DbType="Decimal(18,5) NOT NULL")]
		public decimal calories
		{
			get
			{
				return this._calories;
			}
			set
			{
				if ((this._calories != value))
				{
					this.OncaloriesChanging(value);
					this.SendPropertyChanging();
					this._calories = value;
					this.SendPropertyChanged("calories");
					this.OncaloriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Distancia", Storage="_distance", DbType="Decimal(18,5) NOT NULL")]
		public decimal distance
		{
			get
			{
				return this._distance;
			}
			set
			{
				if ((this._distance != value))
				{
					this.OndistanceChanging(value);
					this.SendPropertyChanging();
					this._distance = value;
					this.SendPropertyChanged("distance");
					this.OndistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Duracion", Storage="_duration", DbType="Int NOT NULL")]
		public int duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Pausas", Storage="_pauses", DbType="Int NOT NULL")]
		public int pauses
		{
			get
			{
				return this._pauses;
			}
			set
			{
				if ((this._pauses != value))
				{
					this.OnpausesChanging(value);
					this.SendPropertyChanging();
					this._pauses = value;
					this.SendPropertyChanged("pauses");
					this.OnpausesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Imagen", Storage="_image", DbType="VarChar(2048) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Velocidad", Storage="_speed", DbType="Decimal(18,5) NOT NULL")]
		public decimal speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this.OnspeedChanging(value);
					this.SendPropertyChanging();
					this._speed = value;
					this.SendPropertyChanged("speed");
					this.OnspeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Compartida", Storage="_isShared", DbType="Int NOT NULL")]
		public int isShared
		{
			get
			{
				return this._isShared;
			}
			set
			{
				if ((this._isShared != value))
				{
					this.OnisSharedChanging(value);
					this.SendPropertyChanging();
					this._isShared = value;
					this.SendPropertyChanged("isShared");
					this.OnisSharedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Nombre", Storage="_shared_name", DbType="VarChar(500)")]
		public string shared_name
		{
			get
			{
				return this._shared_name;
			}
			set
			{
				if ((this._shared_name != value))
				{
					this.Onshared_nameChanging(value);
					this.SendPropertyChanging();
					this._shared_name = value;
					this.SendPropertyChanged("shared_name");
					this.Onshared_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_MeGusta", Storage="_shared_likes", DbType="Int")]
		public System.Nullable<int> shared_likes
		{
			get
			{
				return this._shared_likes;
			}
			set
			{
				if ((this._shared_likes != value))
				{
					this.Onshared_likesChanging(value);
					this.SendPropertyChanging();
					this._shared_likes = value;
					this.SendPropertyChanged("shared_likes");
					this.Onshared_likesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Observaciones", Storage="_shared_observations", DbType="VarChar(500)")]
		public string shared_observations
		{
			get
			{
				return this._shared_observations;
			}
			set
			{
				if ((this._shared_observations != value))
				{
					this.Onshared_observationsChanging(value);
					this.SendPropertyChanging();
					this._shared_observations = value;
					this.SendPropertyChanged("shared_observations");
					this.Onshared_observationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Fecha", Storage="_shared_createdAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> shared_createdAt
		{
			get
			{
				return this._shared_createdAt;
			}
			set
			{
				if ((this._shared_createdAt != value))
				{
					this.Onshared_createdAtChanging(value);
					this.SendPropertyChanging();
					this._shared_createdAt = value;
					this.SendPropertyChanged("shared_createdAt");
					this.Onshared_createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TISE_Nombre", Storage="_sensation_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sensation_name
		{
			get
			{
				return this._sensation_name;
			}
			set
			{
				if ((this._sensation_name != value))
				{
					this.Onsensation_nameChanging(value);
					this.SendPropertyChanging();
					this._sensation_name = value;
					this.SendPropertyChanged("sensation_name");
					this.Onsensation_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TISE_Token", Storage="_sensation_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid sensation_token
		{
			get
			{
				return this._sensation_token;
			}
			set
			{
				if ((this._sensation_token != value))
				{
					this.Onsensation_tokenChanging(value);
					this.SendPropertyChanging();
					this._sensation_token = value;
					this.SendPropertyChanged("sensation_token");
					this.Onsensation_tokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TISE_Identificador", Storage="_sensation_identifier")]
		public string sensation_identifier
		{
			get
			{
				return this._sensation_identifier;
			}
			set
			{
				if ((this._sensation_identifier != value))
				{
					this.Onsensation_identifierChanging(value);
					this.SendPropertyChanging();
					this._sensation_identifier = value;
					this.SendPropertyChanged("sensation_identifier");
					this.Onsensation_identifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Fecha", Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ENTI_Token", Storage="_creator_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid creator_token
		{
			get
			{
				return this._creator_token;
			}
			set
			{
				if ((this._creator_token != value))
				{
					this.Oncreator_tokenChanging(value);
					this.SendPropertyChanging();
					this._creator_token = value;
					this.SendPropertyChanged("creator_token");
					this.Oncreator_tokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ENTI_Identificador", Storage="_creator_identifier", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string creator_identifier
		{
			get
			{
				return this._creator_identifier;
			}
			set
			{
				if ((this._creator_identifier != value))
				{
					this.Oncreator_identifierChanging(value);
					this.SendPropertyChanging();
					this._creator_identifier = value;
					this.SendPropertyChanged("creator_identifier");
					this.Oncreator_identifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ARCH_Token", Storage="_creator_photo", CanBeNull=false)]
		public string creator_photo
		{
			get
			{
				return this._creator_photo;
			}
			set
			{
				if ((this._creator_photo != value))
				{
					this.Oncreator_photoChanging(value);
					this.SendPropertyChanging();
					this._creator_photo = value;
					this.SendPropertyChanged("creator_photo");
					this.Oncreator_photoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUA_NombreCompleto", Storage="_fullname", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string creator_fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.Oncreator_fullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("creator_fullname");
					this.Oncreator_fullnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class newSharedRoute
	{
		
		private string _name;
		
		private string _observation;
		
		public newSharedRoute()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Nombre", Storage="_name", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Observaciones", Storage="_observation", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string observation
		{
			get
			{
				return this._observation;
			}
			set
			{
				if ((this._observation != value))
				{
					this._observation = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VT_MOT_RutasPopulares")]
	public partial class PopularRoute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _token;
		
		private System.DateTime _createdAt;
		
		private System.DateTime _shared_createdAt;
		
		private decimal _altitude;
		
		private decimal _lat;
		
		private decimal _lng;
		
		private decimal _distance;
		
		private int _duration;
		
		private int _pauses;
		
		private string _image;
		
		private decimal _speed;
		
		private string _shared_name;
		
		private int _shared_likes;
		
		private string _shared_observations;
		
		private System.Guid _creator_token;
		
		private string _creator_identifier;
		
		private string _creator_photo;
		
		private string _fullname;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntokenChanging(System.Guid value);
    partial void OntokenChanged();
    partial void OncreatedAtChanging(System.DateTime value);
    partial void OncreatedAtChanged();
    partial void Onshared_createdAtChanging(System.DateTime value);
    partial void Onshared_createdAtChanged();
    partial void OnaltitudeChanging(decimal value);
    partial void OnaltitudeChanged();
    partial void OnlatChanging(decimal value);
    partial void OnlatChanged();
    partial void OnlngChanging(decimal value);
    partial void OnlngChanged();
    partial void OndistanceChanging(decimal value);
    partial void OndistanceChanged();
    partial void OndurationChanging(int value);
    partial void OndurationChanged();
    partial void OnpausesChanging(int value);
    partial void OnpausesChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnspeedChanging(decimal value);
    partial void OnspeedChanged();
    partial void Onshared_nameChanging(string value);
    partial void Onshared_nameChanged();
    partial void Onshared_likesChanging(int value);
    partial void Onshared_likesChanged();
    partial void Onshared_observationsChanging(string value);
    partial void Onshared_observationsChanged();
    partial void Oncreator_tokenChanging(System.Guid value);
    partial void Oncreator_tokenChanged();
    partial void Oncreator_identifierChanging(string value);
    partial void Oncreator_identifierChanged();
    partial void Oncreator_photoChanging(string value);
    partial void Oncreator_photoChanged();
    partial void Oncreator_fullnameChanging(string value);
    partial void Oncreator_fullnameChanged();
    #endregion
		
		public PopularRoute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Token", Storage="_token", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Fecha", Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Fecha", Storage="_shared_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime shared_createdAt
		{
			get
			{
				return this._shared_createdAt;
			}
			set
			{
				if ((this._shared_createdAt != value))
				{
					this.Onshared_createdAtChanging(value);
					this.SendPropertyChanging();
					this._shared_createdAt = value;
					this.SendPropertyChanged("shared_createdAt");
					this.Onshared_createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Altitud", Storage="_altitude", DbType="Decimal(18,5) NOT NULL")]
		public decimal altitude
		{
			get
			{
				return this._altitude;
			}
			set
			{
				if ((this._altitude != value))
				{
					this.OnaltitudeChanging(value);
					this.SendPropertyChanging();
					this._altitude = value;
					this.SendPropertyChanged("altitude");
					this.OnaltitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Latitud", Storage="_lat", DbType="Decimal(18,9) NOT NULL")]
		public decimal lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Longitud", Storage="_lng", DbType="Decimal(18,9) NOT NULL")]
		public decimal lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				if ((this._lng != value))
				{
					this.OnlngChanging(value);
					this.SendPropertyChanging();
					this._lng = value;
					this.SendPropertyChanged("lng");
					this.OnlngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Distancia", Storage="_distance", DbType="Decimal(18,5) NOT NULL")]
		public decimal distance
		{
			get
			{
				return this._distance;
			}
			set
			{
				if ((this._distance != value))
				{
					this.OndistanceChanging(value);
					this.SendPropertyChanging();
					this._distance = value;
					this.SendPropertyChanged("distance");
					this.OndistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Duracion", Storage="_duration", DbType="Int NOT NULL")]
		public int duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Pausas", Storage="_pauses", DbType="Int NOT NULL")]
		public int pauses
		{
			get
			{
				return this._pauses;
			}
			set
			{
				if ((this._pauses != value))
				{
					this.OnpausesChanging(value);
					this.SendPropertyChanging();
					this._pauses = value;
					this.SendPropertyChanged("pauses");
					this.OnpausesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Imagen", Storage="_image", DbType="VarChar(2048) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUTA_Velocidad", Storage="_speed", DbType="Decimal(18,5) NOT NULL")]
		public decimal speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this.OnspeedChanging(value);
					this.SendPropertyChanging();
					this._speed = value;
					this.SendPropertyChanged("speed");
					this.OnspeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Nombre", Storage="_shared_name", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string shared_name
		{
			get
			{
				return this._shared_name;
			}
			set
			{
				if ((this._shared_name != value))
				{
					this.Onshared_nameChanging(value);
					this.SendPropertyChanging();
					this._shared_name = value;
					this.SendPropertyChanged("shared_name");
					this.Onshared_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_MeGusta", Storage="_shared_likes", DbType="Int NOT NULL")]
		public int shared_likes
		{
			get
			{
				return this._shared_likes;
			}
			set
			{
				if ((this._shared_likes != value))
				{
					this.Onshared_likesChanging(value);
					this.SendPropertyChanging();
					this._shared_likes = value;
					this.SendPropertyChanged("shared_likes");
					this.Onshared_likesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Observaciones", Storage="_shared_observations", DbType="VarChar(500)")]
		public string shared_observations
		{
			get
			{
				return this._shared_observations;
			}
			set
			{
				if ((this._shared_observations != value))
				{
					this.Onshared_observationsChanging(value);
					this.SendPropertyChanging();
					this._shared_observations = value;
					this.SendPropertyChanged("shared_observations");
					this.Onshared_observationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ENTI_Token", Storage="_creator_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid creator_token
		{
			get
			{
				return this._creator_token;
			}
			set
			{
				if ((this._creator_token != value))
				{
					this.Oncreator_tokenChanging(value);
					this.SendPropertyChanging();
					this._creator_token = value;
					this.SendPropertyChanged("creator_token");
					this.Oncreator_tokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ENTI_Identificador", Storage="_creator_identifier", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string creator_identifier
		{
			get
			{
				return this._creator_identifier;
			}
			set
			{
				if ((this._creator_identifier != value))
				{
					this.Oncreator_identifierChanging(value);
					this.SendPropertyChanging();
					this._creator_identifier = value;
					this.SendPropertyChanged("creator_identifier");
					this.Oncreator_identifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ARCH_Token", Storage="_creator_photo", CanBeNull=false)]
		public string creator_photo
		{
			get
			{
				return this._creator_photo;
			}
			set
			{
				if ((this._creator_photo != value))
				{
					this.Oncreator_photoChanging(value);
					this.SendPropertyChanging();
					this._creator_photo = value;
					this.SendPropertyChanged("creator_photo");
					this.Oncreator_photoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUA_NombreCompleto", Storage="_fullname", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string creator_fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.Oncreator_fullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("creator_fullname");
					this.Oncreator_fullnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class RoutePhoto
	{
		
		private string _photo;
		
		public RoutePhoto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", CanBeNull=false)]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this._photo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class SocialRoute
	{
		
		private bool _like;
		
		private string _shared_name;
		
		private System.Nullable<int> _shared_likes;
		
		private string _shared_observations;
		
		private System.Nullable<System.DateTime> _shared_createdAt;
		
		public SocialRoute()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="MeGusta", Storage="_like")]
		public bool like
		{
			get
			{
				return this._like;
			}
			set
			{
				if ((this._like != value))
				{
					this._like = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Nombre", Storage="_shared_name", DbType="VarChar(500)")]
		public string name
		{
			get
			{
				return this._shared_name;
			}
			set
			{
				if ((this._shared_name != value))
				{
					this._shared_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_MeGusta", Storage="_shared_likes", DbType="Int")]
		public System.Nullable<int> totalLikes
		{
			get
			{
				return this._shared_likes;
			}
			set
			{
				if ((this._shared_likes != value))
				{
					this._shared_likes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Observaciones", Storage="_shared_observations", DbType="VarChar(500)")]
		public string observations
		{
			get
			{
				return this._shared_observations;
			}
			set
			{
				if ((this._shared_observations != value))
				{
					this._shared_observations = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="RUCO_Fecha", Storage="_shared_createdAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> sharedAt
		{
			get
			{
				return this._shared_createdAt;
			}
			set
			{
				if ((this._shared_createdAt != value))
				{
					this._shared_createdAt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
