#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Endpoints.Ambassadors.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MotoApp_v1")]
	public partial class AmbassadorsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAmbassador(Ambassador instance);
    partial void UpdateAmbassador(Ambassador instance);
    partial void DeleteAmbassador(Ambassador instance);
    #endregion
		
		public AmbassadorsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MotoApp_v1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AmbassadorsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AmbassadorsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AmbassadorsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AmbassadorsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ambassador> Ambassadors
		{
			get
			{
				return this.GetTable<Ambassador>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VT_Embajadores")]
	public partial class Ambassador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _token;
		
		private System.DateTime _createdAt;
		
		private string _identifier;
		
		private System.Nullable<System.Guid> _photo;
		
		private string _email;
		
		private string _name;
		
		private System.DateTime _lastConnection;
		
		private bool _follow;
		
		private int _followers;
		
		private int _following;
		
		private int _likes;
		
		private string _sport_name;
		
		private string _sport_description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntokenChanging(System.Guid value);
    partial void OntokenChanged();
    partial void OncreatedAtChanging(System.DateTime value);
    partial void OncreatedAtChanged();
    partial void OnidentifierChanging(string value);
    partial void OnidentifierChanged();
    partial void OnphotoChanging(System.Nullable<System.Guid> value);
    partial void OnphotoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnlastConnectionChanging(System.DateTime value);
    partial void OnlastConnectionChanged();
    partial void OnfollowChanging(bool value);
    partial void OnfollowChanged();
    partial void OnfollowersChanging(int value);
    partial void OnfollowersChanged();
    partial void OnfollowingChanging(int value);
    partial void OnfollowingChanged();
    partial void OnlikesChanging(int value);
    partial void OnlikesChanged();
    partial void Onsport_nameChanging(string value);
    partial void Onsport_nameChanged();
    partial void Onsport_descriptionChanging(string value);
    partial void Onsport_descriptionChanged();
    #endregion
		
		public Ambassador()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ENTI_Token", Storage="_token", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ENTI_FechaCreacion", Storage="_createdAt", DbType="DateTime NOT NULL")]
		public System.DateTime createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ENTI_Identificador", Storage="_identifier", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this.OnidentifierChanging(value);
					this.SendPropertyChanging();
					this._identifier = value;
					this.SendPropertyChanged("identifier");
					this.OnidentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ARCH_Token", Storage="_photo", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this.OnphotoChanging(value);
					this.SendPropertyChanging();
					this._photo = value;
					this.SendPropertyChanged("photo");
					this.OnphotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUA_Email", Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUA_NombreCompleto", Storage="_name", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUA_UltimaConexion", Storage="_lastConnection", DbType="DateTime NOT NULL")]
		public System.DateTime lastConnection
		{
			get
			{
				return this._lastConnection;
			}
			set
			{
				if ((this._lastConnection != value))
				{
					this.OnlastConnectionChanging(value);
					this.SendPropertyChanging();
					this._lastConnection = value;
					this.SendPropertyChanged("lastConnection");
					this.OnlastConnectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Siguiendo", Storage="_follow")]
		public bool follow
		{
			get
			{
				return this._follow;
			}
			set
			{
				if ((this._follow != value))
				{
					this.OnfollowChanging(value);
					this.SendPropertyChanging();
					this._follow = value;
					this.SendPropertyChanged("follow");
					this.OnfollowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SOCU_Seguidores", Storage="_followers", DbType="Int NOT NULL")]
		public int followers
		{
			get
			{
				return this._followers;
			}
			set
			{
				if ((this._followers != value))
				{
					this.OnfollowersChanging(value);
					this.SendPropertyChanging();
					this._followers = value;
					this.SendPropertyChanged("followers");
					this.OnfollowersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SOCU_Siguiendo", Storage="_following", DbType="Int NOT NULL")]
		public int following
		{
			get
			{
				return this._following;
			}
			set
			{
				if ((this._following != value))
				{
					this.OnfollowingChanging(value);
					this.SendPropertyChanging();
					this._following = value;
					this.SendPropertyChanged("following");
					this.OnfollowingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SOCU_MeGusta", Storage="_likes", DbType="Int NOT NULL")]
		public int likes
		{
			get
			{
				return this._likes;
			}
			set
			{
				if ((this._likes != value))
				{
					this.OnlikesChanging(value);
					this.SendPropertyChanging();
					this._likes = value;
					this.SendPropertyChanged("likes");
					this.OnlikesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TIDE_Nombre", Storage="_sport_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sport_name
		{
			get
			{
				return this._sport_name;
			}
			set
			{
				if ((this._sport_name != value))
				{
					this.Onsport_nameChanging(value);
					this.SendPropertyChanging();
					this._sport_name = value;
					this.SendPropertyChanged("sport_name");
					this.Onsport_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TIDE_Descripcion", Storage="_sport_description", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string sport_description
		{
			get
			{
				return this._sport_description;
			}
			set
			{
				if ((this._sport_description != value))
				{
					this.Onsport_descriptionChanging(value);
					this.SendPropertyChanging();
					this._sport_description = value;
					this.SendPropertyChanged("sport_description");
					this.Onsport_descriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
