<?xml version="1.0" encoding="utf-8"?><Database Name="MotoApp_v1" Class="ProfileDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\MSSQLSERVER_2012;Initial Catalog=MotoApp_v1;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MotoApp_v1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_MOT_ContadorSocial" Member="SocialProfiles">
    <Type Name="SocialProfile">
      <Column Name="SOCU_Seguidores" Member="followers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOCU_Siguiendo" Member="following" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOCU_MeGusta" Member="likes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RUTA_Distancia" Member="distance" Type="System.Decimal" DbType="Decimal(18,5) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TB_MOT_TipoDeporte" Member="Sports">
    <Type Name="Sport">
      <Column Name="TIDE_Nombre" Member="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TIDE_Descripcion" Member="description" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.V_Perfiles" Member="Roles">
    <Type Name="Role">
      <Column Name="ENTI_Nombre" Member="name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ENTI_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PERF_Identificador" Member="identifier" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VT_Usuarios" Member="Accounts">
    <Type Name="Account">
      <Column Name="ENTI_Token" Member="token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ENTI_FechaCreacion" Member="createdAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ENTI_Identificador" Member="identifier" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ARCH_Token" Member="photo" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="USUA_Email" Member="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="USUA_NombreCompleto" Member="name" Storage="_fullname" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="USUA_UltimaConexion" Member="lastConnection" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="USUA_Activo" Member="active" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
</Database>